version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'laravel'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: 'laravel'
    ports:
      - "3306:3306"
  app:
    build: docker/web
    command: [
      'prehook', 'php composer.phar install', '--',
      'prehook', 'chown -R root:apache /data/www/storage', '--',
      'prehook', 'chmod -R 755 /data/www/storage', '--',
      'codep',
        '/usr/sbin/httpd -D FOREGROUND'
    ]
    volumes:
      - .:/data/www
      - vendor_php:/data/www/vendor
    ports:
      - 8080:80
volumes:
  mysql_data:
    driver: local
  vendor_php:
    driver: local