FROM mysql:5.7
MAINTAINER Ngo Van Thang <thangnvbkhn@gmail.com>

# Set TERM env to avoid mysql client error message "TERM environment variable not set" when running from inside the container
ENV TERM xterm

# Docker側でlistenするポート番号を指定
EXPOSE 3306
